sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - npm install -g bower
  - npm install -g gulp

before_script:
  - ./gradlew npmInstall

script:
  - ./gradlew docker


after_success:
  - docker login  -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag  lumue/getdown:master-SNAPSHOT lumue/getdown:latest
  - docker push lumue/getdown:master-SNAPSHOT
  - docker push lumue/getdown:latest

