version: '3.5'

services:

  getdown:
    image: lumue/getdown:master-SNAPSHOT
    restart: always
    volumes:
      - ./getdown:/getdown
      - /mnt/truenas/downloads/:/downloads
    ports:
      - "7001:8001"
    environment:
      - LANG=C.UTF-8
      - JAVA_OPTS="-Dfile.encoding=UTF-8"



