@startuml
interface DownloadJob{
    Download start(DownloadJobExecutionContext context)
    void resume(Download download)
    void restart(Download download)
    void cancel()
}
note top:execute a single Download in a specific way

class YoutubeDownloadJob
YoutubeDownloadJob -up-|> DownloadJob

class DownloadJobExecutor{
    Download execute(DownloadJob job,DownloadJobExecutionContext context)
}
note top:manage the execution of jobs

class Download{
    DownloadProgress getProgress()
    DownloadJobExecutionContext getContext()
    onUpdate(Function callback)
}
note top:provide info about a concrete execution of a job

interface DownloadParameter{
    URL getUrl()
}
note top:provide parameters for a DownloadJob execution

@enduml