@startuml


interface DownloadJob
note top:defines what should be executed
class YoutubeDownloadJob
YoutubeDownloadJob -up-|> DownloadJob

interface DownloadJobExecutor{
    DownloadJobExecution execute()
}
note top:manage the execution of jobs

interface DownloadJobExecution
note top:provide info about a concrete execution of a job

interface DownloadJobExecutionRequest
note top:provide parameters about a concrete execution of a job

@enduml